service: nextjs-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    NODE_ENV: production

functions:
  nextApp:
    handler: handler.render
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-nextjs-plugin
