name: NC ACADEMY DevSecOps PIPELINE

on:
  push:
    branches:
      - development
      - production
  repository_dispatch:
    types: [deploy-production]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'development' }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t ncacademy_website ./ncacademy_website

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/production' && 'production' || 'development' }}
    steps:
    - name: Run Tests
      run: echo "Running tests"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.TF_VAR_AWS_REGION }}

    - name: Set Environment Variable
      run: echo "TF_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init -var="environment=${{ env.TF_ENV }}"
      working-directory: ./ncacademy_website
    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ./ncacademy_website
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_AWS_REGION: ${{ secrets.TF_VAR_AWS_REGION }}
        TF_VAR_CLOUDFLARE_API_KEY: ${{ secrets.TF_VAR_CLOUDFLARE_API_KEY }}
        TF_VAR_SITE_DOMAIN: ${{ secrets.TF_VAR_SITE_DOMAIN }}

  promote:
    if: github.ref == 'refs/heads/development' && success()
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'development'
        fetch-depth: 0 
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Merge main into production
        run: |
          git checkout production
          git merge main --no-edit
          git push origin production